server:
  servlet:
    context-path: /bot-guard

spring:
  application:
    name: BotGuard
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: true

infrastructure:
  adapters:
    output:
      rest:
        ip.api.baseUrl: http://ip-api.com
      cache:
        rate-limiter:
          ip:
            capacity: 100
            refill:
              tokens: 10
              period: 1m

resilience4j.circuitbreaker:
  instances:
    ip-api-circuit-breaker:
      registerHealthIndicator: true
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: TIME_BASED

logging:
  level:
    com.github.madaaraisok: DEBUG